building_names = {
    "buildingId01":"Woodcutter",
    "buildingId02":"Clay Pit",
    "buildingId03":"Iron Mine",
    "buildingId04":"Cropland",
    "buildingId05":"Sawmill",
    "buildingId06":"Brickyard",
    "buildingId07":"Iron Foundry",
    "buildingId08":"Grain Mill",
    "buildingId09":"Bakery",
    "buildingId10":"Warehouse",
    "buildingId11":"Granary",
    "buildingId12":"",
    "buildingId13":"Smithy",
    "buildingId14":"Tournament Square",
    "buildingId15":"Main Building",
    "buildingId16":"Rally Point",
    "buildingId17":"Marketplace",
    "buildingId18":"Embassy",
    "buildingId19":"Barracks",
    "buildingId20":"Stable",
    "buildingId21":"Workshop",
    "buildingId22":"Academy",
    "buildingId23":"Cranny",
    "buildingId24":"Town Hall",
    "buildingId25":"Residence",
    "buildingId26":"Palace",
    "buildingId27":"Unknown Building",
    "buildingId28":"Trade Office",
    "buildingId29":"Unknown Building",
    "buildingId30":"Unknown Building",
    "buildingId31":"City Wall",
    "buildingId33":"Palisade",
    "buildingId34":"Stonemason's Lodge",
    "buildingId36":"Trapper",
    "buildingId41":"Horse Drinking Trough",
    "buildingId45":"Hidden Treasury",
    "buildingId46":"Healing Tent",
}


